name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: "deploy-main"
  cancel-in-progress: true

env:
  DEPLOYMENT_URL: https://tozydev.id.vn

jobs:
  call-export:
    uses: .github/workflows/export-site.shared.yml
    with:
      upload-traces: true
      upload-site: true

  deploy:
    environment:
      name: Cloudflare Workers
      url: ${{ env.DEPLOYMENT_URL }}

    runs-on: ubuntu-latest
    needs: call-export
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: site

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: latest
